{popular: true , type: 'appetizer', menuNumber: 1 , title:"Fried Egg Rolls", price: 3.75 , description:"Mixed vegetables and glass noodles wrapped in rice paper, served with a sweet and sour sauce."},
{popular: false , type: 'appetizer', menuNumber: 2 , title:"Fresh Rolls", price: 3.50, description:"Vegetables, tofu and noodles wrapped in steamed rice paper served with a sweet & sour sauce."},
{popular: false, type: 'appetizer', menuNumber: 3 , title:"Fried Tofu", price: 4.50 , description:"Crispy tofu served with a sweet and sour sauce with ground peanuts."},
{popular: true , type: 'appetizer', menuNumber: 4 , title:"Chicken Satay", price: 6.00 , description:"Grilled marinated chicken on skewers served with a peanut sauce and cucumber salad."},
{popular: false , type: 'appetizer', menuNumber: 5 , title:"Shrimp Wonton", price: 6.00 , description:"Deep fried shrimp wrapped by wonton skin served with a sweet and sour sauce."},
{popular: true , type: 'appetizer', menuNumber: 6 , title:"Golden Squid", price: 6.00 , description:"Crispy Golden Fried Squid, served with spicy chili peanut sauce"},


{popular: true , type: 'soup', menuNumber: 7 , title:"Tom-Ka Gai", price: 4.95 , description:"A combination of chicken, lemon grass, lime juice, cilantro, red onion, and mushroom in coconut milk blended with special broth."},
{popular: false , type: 'soup', menuNumber: 8 , title:"Tom-Yum Talae", price: 7.95 , description:"Thai spicy seafood soup with lemon grass, lime juice, chili paste, sweet basil, cilantro, red onion and mushroom."},
{popular: false , type: 'soup', menuNumber: 9 , title:"Tom-Yum Gai", price: 6.95 , description:"Thai signature spicy soup with chicken, lemon grass, lime juice, chili paste, cilantro, red onion and mushroom in shrimp broth."},
{popular: true , type: 'entree', menuNumber:10 , title:"Pad Thai", price:10.95 , description:"Classic stir-fried rice noodle with egg, green onion, bean sprout and side of crushed peanut and lime in special Pad Thai sauce."},
{popular: false , type: 'entree', menuNumber:11 , title:"Pad See-U", price:10.95 , description:"Stir-fried broad noodle with egg, broccoli and carrot in delicious sweet-garlic sauce."},
{popular: false, type: 'entree', menuNumber: 12 , title:"Pad Kee-Mao", price: 11.95 , description:" Stir-fried broad noodles with egg, sweet basil, fresh chili, garlic, green bean, onion, tomato and red/green bell pepper."},
{popular: true, type: 'entree', menuNumber: 13 , title:"", price: 10.95 , description:"Thai style rice noodle soup in flavored broth with fried garlic, scallion, bean sprout and cilantro."},
{popular: false, type: 'entree', menuNumber: 14 , title:"Pineapple Fried Rice", price: 11.95 , description:"Special fried rice stir-fried with pineapple, raisin, cashew nut, onion, green pea, tomato, and Thai curry powder."},
{popular: true, type: 'entree', menuNumber: 15 , title:"Yellow Curry", price: 11.95 , description:"Thai yellow curry cooked in cream of coconut with potato, sweet potato, pineapple and onion"},
{popular: false , type: 'entree', menuNumber: 16 , title:"Panang Curry", price: 11.95, description:"Special Panang curry paste cooked in cream of coconut with broccoli, zucchini, carrot, baby corn and snow pea."},
{popular: true , type: 'entree', menuNumber: 17 , title:"Green Curry", price: 11.95 , description:"Sweet & Spicy green curry paste in cream of coconut with sweet basil, bamboo shoot, zucchini, green pea, snow pea, baby corn and eggplant."},
{popular: true , type: 'entree', menuNumber:18 , title:"Gang Ped Yang", price: 16.95 , description:"Semi-crispy duck cooked in red curry sauce bamboo shoot, sweet basil, bell pepper, tomato, green bean, baby corn, green bean, eggplant and pineapple."},
{popular: true , type: 'entree', menuNumber: 19 , title:"Garlic Soft Shell Crab ", price: 19.95 , description:"(2) whole soft shell crab, lightly battered and deep-fried, topped with stir-fried garlic and pepper sauce along with broccoli, carrot, zucchini, onion, snow pea, and baby corn"},
